// <auto-generated />
namespace CRM.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddAttributesToValidateEmailAndPhone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAttributesToValidateEmailAndPhone));
        
        string IMigrationMetadata.Id
        {
            get { return "202104070527151_AddAttributesToValidateEmailAndPhone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
